const SOCKET_TYPES = {
  DASHBOARD: 'SOCKET_TYPES_DASHBOARD',
  BATTLE: 'SOCKET_TYPES_BATTLE',
};

const USER_ROOM_STATES = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTED: 'CONNECTED',
  READY: 'READY',
};

module.exports = {
  SOCKET_TYPES,
  USER_ROOM_STATES,
};
