const SOCKET_TYPES = {
  DASHBOARD: 'SOCKET_TYPES_DASHBOARD',
  BATTLE: 'SOCKET_TYPES_BATTLE',
};

const USER_ROOM_STATES = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTED: 'CONNECTED',
  READY: 'READY',
};

const USER_BATTLE_STATES = {
  DISCONNECTED: 'DISCONNECTED',
  ONLINE: 'ONLINE',
  SLOW_CONNECTION: 'SLOW_CONNECTION',
};

module.exports = {
  SOCKET_TYPES,
  USER_ROOM_STATES,
  USER_BATTLE_STATES,
};
